import uproot
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the ROOT tree generated by your GATE 10 PhaseSpaceActor
file_path = "./output_annihilation/annihilation_data.root"
file = uproot.open(file_path)
tree = file["AnnihilationTracker"]

# 2. Extract relevant branches into a Pandas DataFrame
df = tree.arrays(["KineticEnergy", "ProcessName"], library="pd")

# 3. Filter specifically for the annihilation process ("annihil")
# In GATE/Geant4, 'annihil' handles both at-rest and in-flight processes
annihilation_data = df[df["ProcessName"] == "annihil"]
ke_mev = annihilation_data["KineticEnergy"]

# 4. Create the plot
plt.figure(figsize=(9, 6))

# Define logarithmic bins to capture everything from 1 eV up to 1 MeV+
# We add a tiny offset (1e-7) so that absolute zero values plot cleanly in the first bin
bins = np.logspace(-7, 1, 100) 

plt.hist(ke_mev, bins=bins, color="crimson", edgecolor="black", alpha=0.75)

# 5. Format labels and styling
plt.xscale("log")
plt.yscale("log") # Log scale on Y helps see the rare in-flight events clearly
plt.title("Positron Kinetic Energy Distribution at Annihilation in Water", fontsize=13, fontweight='bold')
plt.xlabel("Kinetic Energy at Annihilation (MeV)", fontsize=11)
plt.ylabel("Event Count (Log Scale)", fontsize=11)
plt.grid(True, which="both", linestyle="--", alpha=0.5)

# Add clear visual indicators for interpretation
plt.text(1e-6, plt.gca().get_ylim()[1]*0.2, "← Annihilation\nat Rest (~0 eV)", 
         color="darkred", fontsize=10, fontweight="bold")
plt.text(1e-2, plt.gca().get_ylim()[1]*0.02, "Annihilation\nin Flight →", 
         color="navy", fontsize=10, fontweight="bold")

plt.tight_layout()
plt.savefig("positron_annihilation_histogram.png", dpi=300)
plt.show()
